#!/usr/bin/env python3
"""Regenerates tools/module-load-probe.html from whatever is in src/.

Run after adding a module:  python3 tools/gen-module-probe.py

The probe imports every src/*.js and reports any that fail to load, which is
the only typecheck available here (no build step, no node). Keeping the list
generated means a new module is covered the moment it exists, instead of
being silently skipped by a hand-maintained array.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
mods = sorted(str(p.relative_to(ROOT / 'src')).replace('\\', '/')
              for p in (ROOT / 'src').rglob('*.js'))
imports = '\n'.join(f"  import('../src/{m}')," for m in mods)

TEMPLATE = '''<!DOCTYPE html>
<html><body style="margin:0;background:#0a0d1c;color:#e8ecf7;font:13px monospace">
<canvas id="game" width="800" height="450" style="display:none"></canvas>
<pre id="out">loading…</pre>
<script>
  // GENERATED by tools/gen-module-probe.py — do not hand-edit the list below.
  //
  // There is no build step and no node in this environment, so a syntax error
  // in any module otherwise only surfaces as a blank canvas in whichever probe
  // happens to run next. This page loads every module under src/ and reports
  // what failed — the cheapest available typecheck, and the first thing to run
  // after any edit.
  //
  // Loading them all at once matters: headless Chrome's --virtual-time-budget
  // does NOT wait on dynamic import()'s network round-trips, so a version that
  // awaited them one at a time reported "checked 1/41" and stopped. Firing
  // every fetch in the same window is what makes this work headless.
  window.__errors = [];
  window.addEventListener('error', e => {
    window.__errors.push(String(e.message) + (e.filename ? ' @ ' + e.filename.split('/').slice(-2).join('/') : ''));
    const out = document.getElementById('out');
    if (out && out.textContent.startsWith('loading')) {
      out.textContent = '*** page-level error\\nerrors: ' + window.__errors.join(' | ');
    }
  });
</script>
<script type="module">
const names = %s;
const results = await Promise.allSettled([
%s
]);
const failures = [];
results.forEach((r, i) => {
  if (r.status === 'rejected') {
    const e = r.reason;
    failures.push(names[i] + ' :: ' + (e && e.message ? e.message : String(e)));
  }
});
const lines = ['modules checked: ' + names.length];
if (failures.length) {
  lines.push('*** ' + failures.length + ' FAILED TO LOAD');
  failures.forEach(f => lines.push('  FAIL ' + f));
} else {
  lines.push('all modules loaded ok');
}
lines.push('errors: ' + (window.__errors.length ? window.__errors.join(' | ') : 'none'));
document.getElementById('out').textContent = lines.join('\\n');
</script></body></html>
'''

out = ROOT / 'tools' / 'module-load-probe.html'
out.write_text(TEMPLATE % (json.dumps(mods), imports))
print(f'wrote {out.relative_to(ROOT)} for {len(mods)} modules')
